services:

  laravel:

    image: robertsl/la-confianza:latest

    container_name: la-confianza

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./.env:/var/www/html/.env